function subData = importfile(filename)
%IMPORTFILE Import data from a text file
%  SUB029DAY001TASKVISBRATRAININGRUN001 = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  SUB029DAY001TASKVISBRATRAININGRUN001 = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  sub029day001taskvisbraTrainingrun001 = importfile("/Volumes/GoogleDrive-102888221454702880647/My Drive/work/PhD/vwfa_training/data/sub-029/sub-029_day-001_task-visbraTraining_run001", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-May-2022 10:55:41

%% Input handling

% If dataLines is not specified, define defaults
dataLines = [1, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time", "type", "message"];
opts.VariableTypes = ["double", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "message", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["type", "message"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "time", "ThousandsSeparator", ",");

% Import the data
subData = readtable(filename, opts);

end