function outList = importWords(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LOCALIZERWORDS1STATTEMPT = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  LOCALIZERWORDS1STATTEMPT = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  localizerwords1stattempt = importfile("C:\Users\filip\Documents\GitHub\VB_backstage_code\post_selection\localizer_words_1st_attempt.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Aug-2021 14:43:21

dataLines = [1, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "clef";
opts.VariableTypes = "char";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "clef", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "clef", "EmptyFieldRule", "auto");

% Import the data
outList = readtable(filename, opts);

end