%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\filip\Desktop\PHD\code\phd1_vb\LexiqueInfra111\Lexique.Infra.Only.Mots.xlsb
%    Worksheet: Mots
%
% Auto-generated by MATLAB on 15-Feb-2021 11:09:56

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 42);

% Specify sheet and range
opts.Sheet = "Mots";
opts.DataRange = "A5:AP137828";

% Specify column names and types
opts.VariableNames = ["Item", "Phono", "cgram", "grapheme", "assoc", "decomp", "decompTok", "Freq_GP", "FreqTok_GP", "Freq_I_GP", "Freq_I_Tok_GP", "Freq_M_GP", "Freq_M_Tok_GP", "Freq_F_GP", "Freq_F_Tok_GP", "minfreqgraph_GP", "minfreqgraphTok_GP", "regTy_GP", "regTo_GP", "countregTy_GP", "countregTo_GP", "posregTy_GP", "posregTo_GP", "decomp_PG", "decompTok_PG", "Freq_PG", "FreqTok_PG", "Freq_I_PG", "Freq_I_Tok_PG", "Freq_M_PG", "Freq_M_Tok_PG", "Freq_F_PG", "Freq_F_Tok_PG", "minfreqgraph_PG", "minfreqgraphTok_PG", "regTy_PG", "regTo_PG", "countregTy_PG", "countregTo_PG", "posregTy_PG", "posregTo_PG", "complexmoygraph"];
opts.VariableTypes = ["char", "categorical", "categorical", "char", "char", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "double", "double", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "double", "double", "double"];

% Specify variable properties
% opts = setvaropts(opts, ["Item", "grapheme", "assoc", "ConsistancePhonmesGraphmes", "decompTok_PG"], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, ["Item", "Phono", "cgram", "grapheme", "assoc", "ConsistanceGraphmesPhonmes", "decompTok", "RgularitGraphmesPhonmes", "regTo_GP", "ConsistancePhonmesGraphmes", "decompTok_PG", "RgularitPhonmesGraphmes", "regTo_PG"], "EmptyFieldRule", "auto");

% Import the data
infra = readtable("C:\Users\filip\Desktop\PHD\code\phd1_vb\LexiqueInfra111\Lexique.Infra.Only.Mots.xlsb", opts, "UseExcel", true);


%% Clear temporary variables
clear opts